name: publish
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/delete-package-versions@v2
        with: 
          package-name: 'ui'
          token: ${{ secrets.NPM_TOKEN }}
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
      - uses: actions/delete-package-versions@v2
        with: 
          package-name: 'utils'
          token: ${{ secrets.NPM_TOKEN }}
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
      - uses: actions/delete-package-versions@v2
        with: 
          package-name: 'scenes'
          token: ${{ secrets.NPM_TOKEN }}
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
      - uses: actions/delete-package-versions@v2
        with: 
          package-name: 'base'
          token: ${{ secrets.NPM_TOKEN }}
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@psycholog-studio'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
      - name: Install
        run: pnpm install
      - name: build
        run: pnpm release:build
      - name: publish
        run: pnpm release:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}